# Generated by Django 5.0.6 on 2024-06-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='author',
            new_name='musician',
        ),
    ]
