# Generated by Django 5.0.6 on 2024-06-01 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthForm',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=None, max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=11)),
                ('condition', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=None, max_length=5)),
                ('symptoms', models.CharField(default=None, max_length=30)),
                ('vaccine', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=None, max_length=10)),
                ('details', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateField(default=datetime.datetime(2024, 6, 1, 11, 35, 13, 229918))),
            ],
        ),
    ]
